name: Metrics
on:
  schedule: [{cron: "0 * * * *"}] # Every hour
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: lgoensApex
          template: classic
          base: activity, community, repositories, metadata
          config_timezone: America/Mexico_City
          plugin_lines: yes
          plugin_contributors: yes
          plugin_contributors_base: all
          plugin_contributors_sections: commit, pr, lines
