name: Metrics
on:
  schedule: [{cron: "0 0 * * 0"}]  # Every Sunday at midnight
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: lgoensApex
          config_timezone: America/Mexico_City

          base: activity, community, repositories
          plugin_contributors: yes
          plugin_contributors_base: all
          plugin_contributors_sections: commit, pr, lines

          plugin_contributors_repositories: |
            Apex-CS/Apex-ICy-Market-Backend
            Apex-CS/Apex-ICy-Market-FrontEnd

          output_action: commit
          filename: metrics2.svg
